### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by alecandido** [AleCandido/partons#23]
Hi @cschwan, this is mainly for you.

The current solution for coverage is not incredibly simple:
https://github.com/AleCandido/partons/blob/c6840ee3dd6e95406ac7ccbe1c6344816953a46e/.github/workflows/ci.yml#L37-L52
even though it seems to work.

The problem is not much using it, that might be fine, but maintaining in case something starts going wrong.

Is there an explicit reason not to use [`tarpaulin`](https://github.com/xd009642/tarpaulin) or something like?
(the main advantage, for me, it's just that is maintained by someone else)

**Comment by cschwan** [comment]
tarpaulin has two disadvantages:

1. it needs to be compiled and installed (slow) and
2. it's imprecise, which results in spotty coverage reports.

**Comment by alecandido** [comment]
The first problem could be avoided with [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall) (it takes less than 2s, since it's just downloading the binary from GitHub).

About the second one I can only trust you (or try, but at the moment I have little spare time for this).

**Comment by cschwan** [comment]
I'd stick with it as long as it's the 'official' approach: <https://doc.rust-lang.org/rustc/instrument-coverage.html>. As you can see, most of the code comes from this page, though I've gone to some lengths to avoid having to install `jq`.

**Comment by alecandido** [comment]
I thought it was a custom solution, if it's official maintaining is not a problem: if I had to modify, it's just a matter of copy-pasting the code from there (in which case I will use `jq` - after all we're only testing on `ubuntu-latest`, thus I can just add one line, i.e. `sudo apt install jq`).
